name: MIE_Converter
main: FaigerSYS\MIE_Converter\MIE_Converter
version: "1.0.2"
api: ["3.0.0-ALPHA7", "3.0.0-ALPHA8", "3.0.0-ALPHA9", "3.0.0-ALPHA10", "3.0.0-ALPHA11", "3.0.0"]
load: POSTWORLD
author: FaigerSYS
description: "Addon for MapImageEngine to convert images to .mie format"

commands:
  mieconvert:
    description: "Convert image to .mie format"
    permission: "mapimageengine.convert"

permissions:
  mapimageengine.convert:
    default: op
    description: "Allows command usage (/mieconvert)"
