--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FaigerSYS/MapImageEngine
branches:
- master
projects:
  MapImageEngine:
    path: MapImageEngine/
    icon: /MapImageEngine/icon.png
  MIE_Protector:
    path: MIE_Protector/
    icon: /MIE_Protector/icon.png
  MIE_Converter:
    path: MIE_Converter/
    icon: /MIE_Converter/icon.png
...
