name: MapImageEngine
main: FaigerSYS\MapImageEngine\MapImageEngine
version: "1.0.9"
api: ["3.0.0-ALPHA1", "3.0.0-ALPHA2", "3.0.0-ALPHA3", "3.0.0-ALPHA4", "3.0.0-ALPHA5", "3.0.0-ALPHA6", "3.0.0-ALPHA7"]
load: POSTWORLD
author: FaigerSYS
description: "Image engine for MCPE servers"

permissions:
  mapimageengine:
    default: op
    description: "Allows command usage (/mie)"
