name: MapImageEngine
main: FaigerSYS\MapImageEngine\MapImageEngine
version: "1.1.3"
api: ["3.0.0"]
load: POSTWORLD
author: FaigerSYS
description: "Image engine for MC:BE servers"

permissions:
  mapimageengine:
    default: op
    description: "Allows command usage (/mapimageengine)"
